travis:
  secure:
    BINSTAR_TOKEN: fYgjptneAuKgJL3+rRYzjFvTwljqQLUTZxMNrrl+lgEkT95IZX4SzOTC29sJQ6nJq8l4ngVe9LMzswoB1OPsDqgafQUzHgl3oEkyBJQx/KzlURkroW+CMTG0bzA52WxA3df6PLwbDVmNSgW/yO+oS8qk2nJPXqkvPWt2V12a1qJunaI2aa4BESwxFOINoGk6+K1tl5A8irXYJ7GjRQYbJyRUMdCLtOYaDZVTx3y70f7B705vzS36fo5tscqNRuH7dw1sMYHRGBWbIMrciSXCd5phhlz/7oZCvffIjUN8983mSvRVaFqjpttmBJ7ukJaRDM4fFS1prmUS9QWvGUcywjqpXpP5ItFDALYXqS/8EACuZ76SW+3Io3HlcozGnf8+LG2uXd45rW28Eq3K0lPNoHGD5JxiKEe3Hc8eNi8nKwG5qkQwufNM9Mxee9r89jQhJmz12EngVCdiKmDwEBVy6ON972kj8j8e0N6tMiQo1+gm9DEl5wZE99qhps6jWWaFF5zwRGXEvVeIasn4Uh/y1GEz3zM2B116xphC8ONOMel+YvpGYLC/GFvtoGRWvg48xx4wUe+3a8JAEQSz9CWJzuR6jdmn2wIeX+LFpd40JgTc7YkVYwi4M26b56uED404IyOYAjTqUQN+s9nZc2wf2IIqsJxYmZjpxb/eC7eRWMI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
