travis:
  secure:
    BINSTAR_TOKEN: disqGiBhGQS3eFqEXUeZyCAfiNC/47a8jjbVSaYfqA1QhKA1ynuLUE+L7pdHP6CA9Uoqi+w7hKEtJQEMb+3KKzay9VSs2jsItO0qjuuLmdM2Ggi0uBug8xxeOsndh48pxH6RoXm6/fzereY0C+SGT9QJ+P333vejqhv8WhagRVtJTbGauOSi7cl4nFRR21T1wjuRTMV5DnfAo7JUSnBcHIFsJH9AW581EKpU0hj/8MTMlQR8SFHUDwUbR/MF+84zRNAeLaJs6dVNuuWse9AMlrsnU3Z2EAow4PReS9+Pm1nOF1Lpryw9Rrb0jql+pj3ZSDOPrnEGRYVI8WyElw/gochflliI47Sf0EENAQzvLCE2+GbNvvJQfSIVxjdF2+EHlPQtdIiLBfST2vwnev077EV+lXnuR7jlmNQ9pH11ypsjWJ9TxSyS4iKQQYxGl/EpI4ZL0T9y9jM7DuApSVtpsHQTzNmUNd4CX1Zol0edN+GrUgdSyP3r8MXUlE08k2HcqchgiySCqGXENtsYIuzV92NvFiXHCyPShdXzLvzz7cPzImOQiK548TPMnObHXNckyUxglaZdyHEdIjvx61WW5c+mOilf214XgtfvBxcH3o3mFnLuzKr12Q4wSI2cbWBUdLhIHQlNNEEjiyg8guJw9iQa5Ipb6VlMVZdBPgYGnxg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
